### ISSUE TITLE
Doesn't work when tbody are created with ng-repeat

### ISSUE THREAD

**Issue by mimomendez13** [sindu12jun/table-dragger#14]
This code doesn't work for me
tbody
tr ng-repeat="item in elements"
td{{item.name}}/td
td{{item.date}}/td
/tr
/tbody

**Comment by sindu12jun** [comment]
Maybe you should inti table-dragger after the table has totally rendered, use `setTimeout`

**Comment by mimomendez13** [comment]
Better option. I used ng-init="$last && finished()" and set the tableDragger in finished function. This works great!
