### ISSUE TITLE
Row moved

### ISSUE THREAD

**Issue by SergeyMiracle** [sindu12jun/table-dragger#15]
This information does not help to understand witch row was moved `console.log(`drop ${el.nodeName} from ${from} ${mode} to ${to} ${mode}`)`
So how to update sorting on server side?

**Comment by sindu12jun** [comment]
Just get the origin order of the table by yourself(dom operation or other way), sort origin table and get new table in the callback.

**Comment by SergeyMiracle** [comment]
Yeah i got this :) Thx
Forgot to close the issue :)

**Comment by honsa** [comment]
Hello, thank you for this nice litte libary.

I also expected that on drop event the `el` should be the actual moved column/row (depending on mode) instead the whole table. Analog to `from` and `to` which refer to the moved element.
