### ISSUE TITLE
Dynamically Injected  table Column, is not draggable

### ISSUE THREAD

**Issue by javmah** [sindu12jun/table-dragger#29]
Excellent piece of code but there is a Problem.  Dynamically Injected a table Column, is not draggable. I insert table Column with  Class  name "handle sindu_handle" but it didn't work, Anyone Have any Suggestion or fix for this. 
regards.

**Comment by soulhunter1987** [comment]
@sindu12jun I see you have not updated this lib for a long time, do you plan to fix bugs/develop it further?

**Comment by sindu12jun** [comment]
@soulhunter1987 thanks a lot for your excellent idea, i'm gonna fix this bug
