### ISSUE TITLE
unable to set global variable or to call other method inside "dragger.on(event)"

### ISSUE THREAD

**Issue by crmanishkumar** [sindu12jun/table-dragger#43]
dragger.on('drop', (from, to, el, mode) => {
       console.log(`drop ${el.nodeName} from ${from} ${mode} to ${to} ${mode}`);

        this.form = from; // unable to set global varibale.
        this.to = to; // unable to set global varibale.
        this.tableSort(from, to); // unable to call other methods

})

**Comment by charanshaale** [comment]
Even I am facing the same issue. Kindly resolve it ASAP.

**Comment by crmanishkumar** [comment]
@sindu12jun. could you help me with this? I am not able to make a call to the service layer. how can I preserve the changed order of the table?

**Comment by crmanishkumar** [comment]
I achieved using **local storage**. 
Is it the best practice? if no. what is the better solution?
