### ISSUE TITLE
Install table-dagger without import

### ISSUE THREAD

**Issue by spidoche** [sindu12jun/table-dragger#8]
I really like  your demo especially the motion when dragging the columns.

But is there a way to use the script without having to do `import tableDragger from 'table-dragger` 

The doc say "easily add drag-and-drop sorting to your table without jQuery", but if you need a build tool to make the script work, I think you must remove "easily" from the title ;-)

**Comment by sindu12jun** [comment]
Hello, I'm glad you like the plugin. It's totally OK to use table-dragger without build tool. Just import
table-dragger in your script tag, like this: `<script src="../node_modules/table-dragger/dist/table-dragger.min.js"></script>`. And `tableDragger ` will be a global variable.

**Comment by slidenerd** [comment]
How would you install this on codepen

**Comment by MarcusOy** [comment]
I manually copied it into one of my projects and I was receiving an error saying `tableDragger` was not a function, but I found out that I had to do `tableDragger.default`. Example:
```
    var el = document.getElementById('only-body-table');
    var dragger = tableDragger.default(el, {
        mode: 'row',
        dragHandler: '.handle',
        onlyBody: true,
        animation: 300
    });
```
Probably because es6 module syntax wasn't available in my environment and am also not using Webpack.

**Comment by ronyderra** [comment]
just updating  - works fine on type script
import - const tableDragger = require("table-dragger");
usage - 
 useEffect(() => {
        const el = document.getElementById("dndTable");
        tableDragger.default(el, {
            mode: "free",
            onlyBody: false,
            dragHandler: ".handle",
            animation: 300
        })
    }, []);
