### ISSUE TITLE
seems to require webpack

### ISSUE THREAD

**Issue by StoneCypher** [sindu12jun/table-dragger#9]
on trying to bundle with browserify:

```
> browserify -r ./build/crop6.es5.js:crop6 -o build/crop6.es5.cjs.js

Error: Cannot find module '!!./../node_modules/.npminstall/css-loader/0.26.1/css-loader/index.js!./main.css' from '/Users/johnhaugeland/projects/crop6/node_modules/table-dragger/dist'
    at /Users/johnhaugeland/projects/crop6/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/johnhaugeland/projects/crop6/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/johnhaugeland/projects/crop6/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/johnhaugeland/projects/crop6/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/johnhaugeland/projects/crop6/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/johnhaugeland/projects/crop6/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
```

is there a way to use this library where i can just handle the css myself?

**Comment by StoneCypher** [comment]
looks like just commenting out the import line in the installed codebase is enough

'course that's not practicable in the long run; i'd have to post-edit the source on every install

**Comment by sindu12jun** [comment]
Hello, thanks for your issue and pr. I am thinking it is really better to open css api in the plugin, but that is not I'm gonna do recently. I'm gonna rewrite this plugin to get more flexible and more features, and I'm sure to open css manage api.
For now, you can just fork and add the feature you want. Thanks again.

**Comment by StoneCypher** [comment]
I did fork and I did remove the feature I don't want.  That's where the PR came from.  

Please understand that most people don't use webpack, and cannot use your library because of that single line.  If you just made a new file, put that line and then invoked the first, nobody would be excluded while we wait for your new work.

Thank you for responding.  Your library is excellent; one of the most pleasant table draggers I've found in user experience.
